// Package edgebundle assembles a deployable Cloudflare Worker bundle from a
// projected EdgeIR. The bundle is a single self-contained ES module: the generic
// JS runtime (the IR interpreter + cache tiers + geo + origin + entry, embedded
// via go:embed) with this site's IR baked in as a global.
//
// There is NO JavaScript toolchain in the build path (design §2.3: no Node, no
// wrangler, no esbuild). The "bundler" is a deliberately tiny source transform:
// the runtime is written as small ES modules that import from each other; here we
// strip those intra-runtime `import`/`export` lines and concatenate the files in
// dependency order into one module scope, preserving only the entry's
// `export default { fetch }`. The IR is injected as `globalThis.__CADISH_IR__`
// with a version guard, so the worker refuses an IR it does not understand.
package edgebundle

import (
	"embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/cadi-sh/cadish/internal/edgeir"
)

//go:embed runtime/interpreter.js runtime/geo.js runtime/origin.js runtime/cache-tiers.js runtime/entry.js
var runtimeFS embed.FS

// runtimeFiles is the concatenation order: dependencies before dependents
// (interpreter is imported by everything; entry orchestrates and owns the
// `export default`). Keep this order — a dependent must follow its dependency so
// every referenced symbol is already declared in the shared module scope.
var runtimeFiles = []string{
	"interpreter.js",
	"geo.js",
	"origin.js",
	"cache-tiers.js",
	"entry.js",
}

// Bundle returns the worker source for one site's IR: the IR (baked as a global
// with a version guard) followed by the de-modularized runtime. The result is a
// single ES module whose only export is the entry's `export default { fetch }`.
func Bundle(ir edgeir.EdgeIR) (string, error) {
	irJSON, err := json.Marshal(ir)
	if err != nil {
		return "", fmt.Errorf("marshal IR: %w", err)
	}
	var b strings.Builder
	b.WriteString("// Generated by `cadish edge build` — DO NOT EDIT.\n")
	b.WriteString("// Cadish Edge worker: the generic IR-interpreter runtime + this site's baked IR.\n")
	b.WriteString("// One Cadishfile, two runtimes — this is the JS one (see docs/edge.md).\n\n")
	fmt.Fprintf(&b, "globalThis.__CADISH_IR__ = %s;\n", irJSON)
	fmt.Fprintf(&b, "if (globalThis.__CADISH_IR__.irVersion !== %d) {\n", edgeir.IRVersion)
	fmt.Fprintf(&b, "  throw new Error(\"cadish edge: IR version \" + globalThis.__CADISH_IR__.irVersion + \" != runtime %d\");\n", edgeir.IRVersion)
	b.WriteString("}\n\n")

	for _, name := range runtimeFiles {
		src, err := runtimeFS.ReadFile("runtime/" + name)
		if err != nil {
			return "", fmt.Errorf("read embedded runtime/%s: %w", name, err)
		}
		fmt.Fprintf(&b, "// ----- runtime/%s -----\n", name)
		b.WriteString(demodularize(string(src)))
		b.WriteString("\n")
	}
	return b.String(), nil
}

// demodularize strips intra-runtime ES module wiring so the files can share one
// module scope when concatenated: it drops `import … from "./…";` lines (the
// symbols become top-level) and removes the `export ` keyword from named exports,
// while preserving `export default …` (the worker's sole real export). It is
// intentionally line-based and conservative — the runtime is hand-written to keep
// each import on its own line and each export at column 0.
func demodularize(src string) string {
	lines := strings.Split(src, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "import ") && strings.Contains(trimmed, `from "./`):
			// intra-runtime import — drop it (symbol is declared elsewhere in scope).
			continue
		case strings.HasPrefix(line, "export default"):
			out = append(out, line) // the worker's entrypoint — keep verbatim.
		case strings.HasPrefix(line, "export "):
			out = append(out, line[len("export "):]) // named export -> bare declaration.
		default:
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}
